import { useState } from 'react'
import { ArrowDown, BellRing, CheckCircle2, CircleDot, Clock3, FlaskConical, Play, Power, Workflow, Zap } from 'lucide-react'
import { Button } from '../components/Controls'
import type { AutomationRule } from '../domain'
import { useMitraClick } from '../MitraClickContext'
import { formatDate } from '../utils'
import { IntegrationBadge, KpiCard, PageHeader, Panel, StatusBadge } from '../components/Primitives'
import { RecordDrawer } from '../components/RecordDrawer'

function Step({ kind, text, tone }: { kind: string; text: string; tone: 'trigger' | 'condition' | 'action' }) {
  const styles = { trigger: 'bg-blue-50 text-blue-700', condition: 'bg-amber-50 text-amber-700', action: 'bg-emerald-50 text-emerald-700' }
  const icons = { trigger: CircleDot, condition: CheckCircle2, action: Zap }
  const Icon = icons[tone]
  return <div className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-3"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${styles[tone]}`}><Icon size={16} /></span><div className="min-w-0"><p className="text-[9px] font-extrabold uppercase tracking-[0.16em] text-slate-400">{kind}</p><p className="mt-0.5 text-xs font-bold leading-5 text-slate-700">{text}</p></div></div>
}

function AutomationDetail({ rule, onClose }: { rule: AutomationRule; onClose: () => void }) {
  const { toggleAutomation, simulateAutomation } = useMitraClick()
  const [simulated, setSimulated] = useState(false)
  const run = () => { simulateAutomation(rule.id); setSimulated(true) }
  return <RecordDrawer open title={rule.name} subtitle="Regla de automatización simulada" onClose={onClose} footer={<div className="flex items-center justify-between gap-3"><p className={`text-xs ${simulated ? 'font-bold text-emerald-700' : 'text-slate-400'}`}>{simulated ? 'Simulación completada; revisa Actividad.' : 'No se ejecutará ninguna integración externa.'}</p><Button onClick={run}><span className="flex items-center gap-2"><FlaskConical size={15} />Simular regla</span></Button></div>}><div className="space-y-6"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-extrabold text-slate-800">Estado de la regla</p><p className="mt-1 text-xs text-slate-400">Control local de demostración</p></div><button type="button" onClick={() => toggleAutomation(rule.id)} className={`relative h-11 w-14 rounded-full transition ${rule.enabled ? 'bg-emerald-500' : 'bg-slate-300'}`} aria-label={rule.enabled ? 'Desactivar automatización' : 'Activar automatización'}><span className={`absolute top-2 h-7 w-7 rounded-full bg-white shadow-sm transition ${rule.enabled ? 'left-7' : 'left-2'}`} /></button></div></div><section><h3 className="mb-3 text-xs font-extrabold uppercase tracking-[0.16em] text-slate-400">Flujo</h3><div className="space-y-2"><Step kind="Disparador" text={rule.trigger} tone="trigger" /><div className="flex justify-center"><span className="grid h-6 w-6 place-items-center rounded-full border border-slate-200 bg-white text-slate-400"><ArrowDown size={13} /></span></div><Step kind="Condición" text={rule.condition} tone="condition" /><div className="flex justify-center"><span className="grid h-6 w-6 place-items-center rounded-full border border-slate-200 bg-white text-slate-400"><ArrowDown size={13} /></span></div><Step kind="Acción" text={rule.action} tone="action" /></div></section><section><h3 className="mb-3 text-xs font-extrabold uppercase tracking-[0.16em] text-slate-400">Ejecución</h3><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-slate-200 p-3"><p className="text-[10px] font-bold uppercase text-slate-400">Simulaciones</p><p className="mt-1 text-xl font-black text-slate-900">{rule.runCount}</p></div><div className="rounded-xl border border-slate-200 p-3"><p className="text-[10px] font-bold uppercase text-slate-400">Última evaluación</p><p className="mt-1 text-xs font-extrabold text-slate-700">{rule.lastRunAt ? formatDate(rule.lastRunAt, true) : 'Nunca'}</p></div></div></section><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900"><span className="font-extrabold">Pendiente de integración:</span> motor de eventos, programación, asignación real, permisos, auditoría y manejo de fallos.</div></div></RecordDrawer>
}

export function AutomationsPage() {
  const { data, toggleAutomation, simulateAutomation } = useMitraClick()
  const [selectedId, setSelectedId] = useState<string | null>(null)
  if (!data) return null
  const selected = data.automations.find((rule) => rule.id === selectedId)
  const enabled = data.automations.filter((rule) => rule.enabled).length
  const runs = data.automations.reduce((sum, rule) => sum + rule.runCount, 0)

  return <div className="space-y-6"><PageHeader eyebrow="Orquestación" title="Automatizaciones" description="Diseña reglas como Disparador → Condición → Acción. En esta fase sólo se guardan cambios locales y se simula su evaluación." actions={<IntegrationBadge label="Motor real pendiente" />} /><div className="grid gap-3 sm:grid-cols-3"><KpiCard label="Reglas activas" value={enabled} helper={`${data.automations.length} configuradas`} icon={Power} accent="green" /><KpiCard label="Simulaciones" value={runs} helper="Ejecuciones del escenario demo" icon={Play} accent="violet" /><KpiCard label="Alertas preparadas" value={data.automations.filter((rule) => rule.action.toLocaleLowerCase('es-MX').includes('alerta')).length} helper="Sin notificaciones reales" icon={BellRing} accent="amber" /></div><div className="grid gap-4 lg:grid-cols-2">{data.automations.map((rule) => <Panel key={rule.id} className="h-full" padding={false}><div className="p-4"><div className="flex items-start justify-between gap-4"><button type="button" onClick={() => setSelectedId(rule.id)} className="min-w-0 flex-1 text-left"><div className="flex items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-700"><Workflow size={18} /></span><div className="min-w-0"><p className="truncate text-sm font-extrabold text-slate-900">{rule.name}</p><p className="mt-0.5 text-[10px] text-slate-400">{rule.runCount} simulaciones</p></div></div></button><button type="button" onClick={() => toggleAutomation(rule.id)} className={`relative h-11 w-14 shrink-0 rounded-full transition ${rule.enabled ? 'bg-emerald-500' : 'bg-slate-300'}`} aria-label={rule.enabled ? 'Desactivar automatización' : 'Activar automatización'}><span className={`absolute top-2 h-7 w-7 rounded-full bg-white shadow-sm transition ${rule.enabled ? 'left-7' : 'left-2'}`} /></button></div><div className="mt-4 space-y-1.5"><Step kind="Disparador" text={rule.trigger} tone="trigger" /><div className="flex justify-center"><ArrowDown size={14} className="text-slate-300" /></div><Step kind="Condición" text={rule.condition} tone="condition" /><div className="flex justify-center"><ArrowDown size={14} className="text-slate-300" /></div><Step kind="Acción" text={rule.action} tone="action" /></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3"><div className="flex items-center gap-2 text-[10px] text-slate-400"><Clock3 size={13} />{rule.lastRunAt ? formatDate(rule.lastRunAt, true) : 'Sin ejecutar'}</div><div className="flex items-center gap-2"><StatusBadge status={rule.enabled ? 'Activa' : 'Pausada'} /><button type="button" onClick={() => simulateAutomation(rule.id)} className="min-h-11 rounded-xl border border-slate-200 px-3 py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-50">Simular</button></div></div></div></Panel>)}</div>{selected && <AutomationDetail rule={selected} onClose={() => setSelectedId(null)} />}</div>
}
