import { useMemo, useState } from 'react'
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Boxes, Layers3, Search, ShoppingBag, Sparkles, TrendingUp } from 'lucide-react'
import type { Product } from '../domain'
import { useMitraClick } from '../MitraClickContext'
import { formatCurrency, formatNumber } from '../utils'
import { KpiCard, PageHeader, Panel, ProductBar, StatusBadge } from '../components/Primitives'
import { RecordDrawer } from '../components/RecordDrawer'

function ProductDetail({ product, onClose }: { product: Product; onClose: () => void }) {
  const { data } = useMitraClick()
  if (!data) return null
  const opportunities = data.opportunities.filter((item) => item.productIds.includes(product.id))

  return (
    <RecordDrawer open title={product.name} subtitle={`${product.sku} · ${product.brand}`} onClose={onClose}>
      <div className="space-y-6">
        <div className="rounded-2xl bg-gradient-to-br from-[#f7eee8] to-[#fff8f3] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#c94c35]">Inteligencia de producto</p><p className="mt-2 text-2xl font-black text-mc-gray-950">Índice {product.demandIndex}/100</p><p className={`mt-1 text-xs font-bold ${product.trend >= 0 ? 'text-mc-success' : 'text-mc-danger'}`}>{product.trend >= 0 ? '+' : ''}{product.trend}% de tendencia simulada</p></div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white text-[#d65339] shadow-sm"><Sparkles size={21} /></span></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-gradient-to-r from-[#e25f45] to-[#f5a14e]" style={{ width: `${product.demandIndex}%` }} /></div></div>
        <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-mc-gray-200 p-4"><p className="text-[10px] font-bold uppercase text-mc-gray-400">Ventas atribuidas</p><p className="mt-1 text-xl font-black text-mc-gray-900">{formatCurrency(product.salesValue)}</p><p className="mt-1 text-xs text-mc-gray-400">{product.unitsSold} unidades simuladas</p></div><div className="rounded-xl border border-mc-gray-200 p-4"><p className="text-[10px] font-bold uppercase text-mc-gray-400">Interés comercial</p><p className="mt-1 text-xl font-black text-mc-gray-900">{product.leadCount} leads</p><p className="mt-1 text-xs text-mc-gray-400">{product.opportunityCount} oportunidades</p></div><div className="rounded-xl border border-mc-gray-200 p-4"><p className="text-[10px] font-bold uppercase text-mc-gray-400">Categoría</p><p className="mt-1 text-sm font-extrabold text-mc-gray-800">{product.category}</p></div><div className="rounded-xl border border-mc-gray-200 p-4"><p className="text-[10px] font-bold uppercase text-mc-gray-400">Precio de referencia</p><p className="mt-1 text-sm font-extrabold text-mc-gray-800">{formatCurrency(product.price)}</p></div></div>
        <section><h3 className="mb-3 text-xs font-extrabold uppercase tracking-[0.16em] text-mc-gray-400">Oportunidades relacionadas</h3><div className="space-y-2">{opportunities.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-xl border border-mc-gray-200 p-3"><div><p className="text-xs font-extrabold text-mc-gray-800">{item.name}</p><p className="mt-1 text-[11px] text-mc-gray-400">{item.companyName} · {formatCurrency(item.value)}</p></div><StatusBadge status={item.stage} /></div>)}</div></section>
        <div className="rounded-xl border border-blue-100 bg-blue-50 p-4 text-xs leading-5 text-blue-900"><span className="font-extrabold">Alcance:</span> esta pantalla analiza señales comerciales. No permite crear, editar, publicar ni sincronizar productos con Shopify.</div>
      </div>
    </RecordDrawer>
  )
}

export function ProductsPage() {
  const { data } = useMitraClick()
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('Todas')
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const products = useMemo(() => data?.products.filter((product) => (category === 'Todas' || product.category === category) && `${product.name} ${product.category} ${product.brand} ${product.sku}`.toLocaleLowerCase('es-MX').includes(query.toLocaleLowerCase('es-MX'))) ?? [], [category, data, query])
  if (!data) return null
  const categories = ['Todas', ...Array.from(new Set(data.products.map((product) => product.category)))]
  const selected = data.products.find((product) => product.id === selectedId)
  const totalSales = data.products.reduce((sum, product) => sum + product.salesValue, 0)
  const maxDemand = Math.max(...data.products.map((product) => product.demandIndex))

  return (
    <div className="space-y-6">
      <PageHeader eyebrow="Inteligencia comercial" title="Productos" description="Detecta demanda, ventas, leads y oportunidades por producto, categoría y marca. El catálogo permanece fuera del alcance." actions={<span className="rounded-full border border-blue-200 bg-blue-50 px-3 py-1.5 text-[11px] font-bold text-blue-700">Sólo análisis · sin Shopify</span>} />
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Ventas por productos" value={formatCurrency(totalSales, true)} helper="Suma de señales simuladas" icon={ShoppingBag} accent="green" /><KpiCard label="Leads con interés" value={data.products.reduce((sum, item) => sum + item.leadCount, 0)} helper="Puede haber múltiples intereses" icon={Sparkles} accent="coral" /><KpiCard label="Categorías" value={categories.length - 1} helper="Agrupación analítica" icon={Layers3} accent="violet" /><KpiCard label="Demanda máxima" value={`${maxDemand}/100`} helper="Índice sintético" icon={TrendingUp} accent="amber" /></div>
      <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><Panel title="Ventas e interés por producto" description="Compara ingresos simulados contra volumen de leads"><div className="h-[320px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.products} margin={{ left: 0, right: 10, top: 10, bottom: 40 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e9edf2" /><XAxis dataKey="name" angle={-28} textAnchor="end" interval={0} tick={{ fontSize: 9, fill: '#64748b' }} axisLine={false} tickLine={false} /><YAxis yAxisId="sales" tickFormatter={(value) => formatCurrency(Number(value), true)} tick={{ fontSize: 9, fill: '#94a3b8' }} axisLine={false} tickLine={false} width={58} /><YAxis yAxisId="leads" orientation="right" tick={{ fontSize: 9, fill: '#94a3b8' }} axisLine={false} tickLine={false} width={28} /><Tooltip formatter={(value, name) => [name === 'salesValue' ? formatCurrency(Number(value)) : formatNumber(Number(value)), name === 'salesValue' ? 'Ventas' : 'Leads']} contentStyle={{ borderRadius: 12, border: '1px solid #e2e8f0', fontSize: 12 }} /><Bar yAxisId="sales" dataKey="salesValue" fill="#23395d" radius={[5, 5, 0, 0]} /><Bar yAxisId="leads" dataKey="leadCount" fill="#e25f45" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></Panel><Panel title="Índice de demanda" description="Señal sintética preparada para un modelo futuro"><div className="space-y-4">{data.products.slice().sort((a, b) => b.demandIndex - a.demandIndex).map((product) => <ProductBar key={product.id} label={product.name} value={product.demandIndex} max={100} detail={`${product.demandIndex}/100`} />)}</div></Panel></div>
      <Panel padding={false}>
        <div className="flex flex-col gap-3 border-b border-mc-gray-100 p-4 sm:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -tranmc-gray-y-1/2 text-mc-gray-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar producto, categoría, marca o SKU…" className="h-10 w-full rounded-xl border border-mc-gray-200 bg-mc-gray-50/60 pl-9 pr-3 text-sm outline-none focus:border-blue-400" /></div><select value={category} onChange={(event) => setCategory(event.target.value)} className="h-10 rounded-xl border border-mc-gray-200 bg-white px-3 text-xs font-bold text-mc-gray-600">{categories.map((item) => <option key={item}>{item}</option>)}</select></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="bg-mc-gray-50 text-[10px] uppercase tracking-wider text-mc-gray-400"><tr><th className="px-5 py-3">Producto</th><th className="px-4 py-3">Categoría / Marca</th><th className="px-4 py-3 text-right">Precio</th><th className="px-4 py-3 text-right">Ventas</th><th className="px-4 py-3 text-center">Unidades</th><th className="px-4 py-3 text-center">Leads</th><th className="px-4 py-3 text-center">Oportunidades</th><th className="px-5 py-3">Demanda</th></tr></thead><tbody className="divide-y divide-mc-gray-100">{products.map((product) => <tr key={product.id} onClick={() => setSelectedId(product.id)} className="group cursor-pointer hover:bg-blue-50/30"><td className="px-5 py-3"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-orange-50 text-[#d65339]"><Boxes size={17} /></span><div><p className="font-extrabold text-mc-gray-800 group-hover:text-blue-800">{product.name}</p><p className="mt-0.5 text-[10px] text-mc-gray-400">{product.sku}</p></div></div></td><td className="px-4 py-3"><p className="font-semibold text-mc-gray-700">{product.category}</p><p className="mt-0.5 text-[10px] text-mc-gray-400">{product.brand}</p></td><td className="px-4 py-3 text-right font-bold text-mc-gray-700">{formatCurrency(product.price)}</td><td className="px-4 py-3 text-right font-black text-mc-gray-900">{formatCurrency(product.salesValue)}</td><td className="px-4 py-3 text-center font-bold text-mc-gray-600">{product.unitsSold}</td><td className="px-4 py-3 text-center font-bold text-mc-gray-600">{product.leadCount}</td><td className="px-4 py-3 text-center font-bold text-mc-gray-600">{product.opportunityCount}</td><td className="px-5 py-3"><div className="flex items-center gap-2"><div className="h-2 w-20 overflow-hidden rounded-full bg-mc-gray-100"><div className="h-full rounded-full bg-[#e25f45]" style={{ width: `${product.demandIndex}%` }} /></div><span className="font-black text-mc-gray-700">{product.demandIndex}</span></div></td></tr>)}</tbody></table></div>
      </Panel>
      {selected && <ProductDetail product={selected} onClose={() => setSelectedId(null)} />}
    </div>
  )
}
